### ISSUE TITLE
Can't configure MySQL connection's SSL parameters

### ISSUE THREAD

**Issue by hmans** [bruin-data/bruin#338]
As far as I understand how things work under the hood, Bruin will build connection strings from its connection configuration objects that are passed to Ingestr/dlt. These two seem to support MySQL SSL connection parameters through database URLs, but it doesn't seem possible to set these through the MySQL configuration object and struct.

(I may have a go at a PR.)

**Comment by karakanb** [comment]
hey, taking a look at this.
